version: '3.9'

services:
  python-dev:
    build: .
    container_name: python-dev
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    tty: true

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: